package com.myspace.ecommerce;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
@javax.xml.bind.annotation.XmlRootElement
public class CostCalculation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Double cost;
	private java.lang.Double directCost;

	private java.lang.Double nextCost;

	private java.lang.Double allCost;

	public CostCalculation() {
	}

	public java.lang.Double getCost() {
		return this.cost;
	}

	public void setCost(java.lang.Double cost) {
		this.cost = cost;
	}

	public java.lang.Double getDirectCost() {
		return this.directCost;
	}

	public void setDirectCost(java.lang.Double directCost) {
		this.directCost = directCost;
	}

	public java.lang.Double getNextCost() {
		return this.nextCost;
	}

	public void setNextCost(java.lang.Double nextCost) {
		this.nextCost = nextCost;
	}

	public java.lang.Double getAllCost() {
		return this.allCost;
	}

	public void setAllCost(java.lang.Double allCost) {
		this.allCost = allCost;
	}

	public CostCalculation(java.lang.Double cost, java.lang.Double directCost,
			java.lang.Double nextCost, java.lang.Double allCost) {
		this.cost = cost;
		this.directCost = directCost;
		this.nextCost = nextCost;
		this.allCost = allCost;
	}

}