package com.myspace.ecommerce;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DailyCost implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String date;
	private java.lang.Float dailyCost;

	public DailyCost() {
	}

	public java.lang.Float getDailyCost() {
		return this.dailyCost;
	}

	public void setDailyCost(java.lang.Float dailyCost) {
		this.dailyCost = dailyCost;
	}

	public java.lang.String getDate() {
		return this.date;
	}

	public void setDate(java.lang.String date) {
		this.date = date;
	}

	public DailyCost(java.lang.String date, java.lang.Float dailyCost) {
		this.date = date;
		this.dailyCost = dailyCost;
	}

}