package com.myspace.ecommerce;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DeliveryGroup implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String group;
	private java.lang.Float fixedCost;
	private java.lang.Float factor;

	public DeliveryGroup() {
	}

	public java.lang.String getGroup() {
		return this.group;
	}

	public void setGroup(java.lang.String group) {
		this.group = group;
	}

	public java.lang.Float getFixedCost() {
		return this.fixedCost;
	}

	public void setFixedCost(java.lang.Float fixedCost) {
		this.fixedCost = fixedCost;
	}

	public java.lang.Float getFactor() {
		return this.factor;
	}

	public void setFactor(java.lang.Float factor) {
		this.factor = factor;
	}

	public DeliveryGroup(java.lang.String group, java.lang.Float fixedCost,
			java.lang.Float factor) {
		this.group = group;
		this.fixedCost = fixedCost;
		this.factor = factor;
	}

}