package com.myspace.ecommerce;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Flagging implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private boolean flagToday;
	private boolean flagTodayOne;
	private boolean flagTodayTwo;
	private boolean flagTodayThree;
	private boolean flagTodayFour;
	private java.lang.Boolean flagTodayFive;
	private boolean flagTodaySix;

	public Flagging() {
	}

	public boolean isFlagToday() {
		return this.flagToday;
	}

	public void setFlagToday(boolean flagToday) {
		this.flagToday = flagToday;
	}

	public boolean isFlagTodayOne() {
		return this.flagTodayOne;
	}

	public void setFlagTodayOne(boolean flagTodayOne) {
		this.flagTodayOne = flagTodayOne;
	}

	public boolean isFlagTodayTwo() {
		return this.flagTodayTwo;
	}

	public void setFlagTodayTwo(boolean flagTodayTwo) {
		this.flagTodayTwo = flagTodayTwo;
	}

	public boolean isFlagTodayThree() {
		return this.flagTodayThree;
	}

	public void setFlagTodayThree(boolean flagTodayThree) {
		this.flagTodayThree = flagTodayThree;
	}

	public boolean isFlagTodayFour() {
		return this.flagTodayFour;
	}

	public void setFlagTodayFour(boolean flagTodayFour) {
		this.flagTodayFour = flagTodayFour;
	}

	public java.lang.Boolean getFlagTodayFive() {
		return this.flagTodayFive;
	}

	public void setFlagTodayFive(java.lang.Boolean flagTodayFive) {
		this.flagTodayFive = flagTodayFive;
	}

	public boolean isFlagTodaySix() {
		return this.flagTodaySix;
	}

	public void setFlagTodaySix(boolean flagTodaySix) {
		this.flagTodaySix = flagTodaySix;
	}

	public Flagging(boolean flagToday, boolean flagTodayOne,
			boolean flagTodayTwo, boolean flagTodayThree,
			boolean flagTodayFour, java.lang.Boolean flagTodayFive,
			boolean flagTodaySix) {
		this.flagToday = flagToday;
		this.flagTodayOne = flagTodayOne;
		this.flagTodayTwo = flagTodayTwo;
		this.flagTodayThree = flagTodayThree;
		this.flagTodayFour = flagTodayFour;
		this.flagTodayFive = flagTodayFive;
		this.flagTodaySix = flagTodaySix;
	}

}