package com.myspace.ecommerce;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RushHours implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private float cost;
	private int time;

	private String date;

	public RushHours() {
	}

	public float getCost() {
		return this.cost;
	}

	public void setCost(float cost) {
		this.cost = cost;
	}

	public int getTime() {
		return this.time;
	}

	public void setTime(int time) {
		this.time = time;
	}

	public java.lang.String getDate() {
		return this.date;
	}

	public void setDate(java.lang.String date) {
		this.date = date;
	}

	public RushHours(float cost, int time, java.lang.String date) {
		this.cost = cost;
		this.time = time;
		this.date = date;
	}

}