package com.myspace.ecommerce;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ServiceLeadTime implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private float kgFactor;

	private float kmFactor;

	private java.lang.Integer fixedCost;

	private java.lang.Integer leadTime;

	public ServiceLeadTime() {
	}

	public float getKgFactor() {
		return this.kgFactor;
	}

	public void setKgFactor(float kgFactor) {
		this.kgFactor = kgFactor;
	}

	public float getKmFactor() {
		return this.kmFactor;
	}

	public void setKmFactor(float kmFactor) {
		this.kmFactor = kmFactor;
	}

	public java.lang.Integer getFixedCost() {
		return this.fixedCost;
	}

	public void setFixedCost(java.lang.Integer fixedCost) {
		this.fixedCost = fixedCost;
	}

	public java.lang.Integer getLeadTime() {
		return this.leadTime;
	}

	public void setLeadTime(java.lang.Integer leadTime) {
		this.leadTime = leadTime;
	}

	public ServiceLeadTime(float kgFactor, float kmFactor,
			java.lang.Integer fixedCost, java.lang.Integer leadTime) {
		this.kgFactor = kgFactor;
		this.kmFactor = kmFactor;
		this.fixedCost = fixedCost;
		this.leadTime = leadTime;
	}

}