package com.myspace.ecommerce;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ShipToCity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String stCity;

	public ShipToCity() {
	}

	public java.lang.String getStCity() {
		return this.stCity;
	}

	public void setStCity(java.lang.String stCity) {
		this.stCity = stCity;
	}

	public ShipToCity(java.lang.String stCity) {
		this.stCity = stCity;
	}

}