package com.myspace.ecommerce;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ShipfromCity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String sfCity;

	public ShipfromCity() {
	}

	public java.lang.String getSfCity() {
		return this.sfCity;
	}

	public void setSfCity(java.lang.String sfCity) {
		this.sfCity = sfCity;
	}

	public ShipfromCity(java.lang.String sfCity) {
		this.sfCity = sfCity;
	}

}