package com.myspace.ecommerce;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Solution implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private boolean flag1;
	private boolean flag2;
	private boolean flag3;
	private boolean flag4;
	private boolean flag5;
	private boolean flag6;
	private boolean flag7;
	private boolean flag8;
	private boolean flag9;
	private boolean flag10;

	public Solution() {
	}

	public boolean isFlag1() {
		return this.flag1;
	}

	public void setFlag1(boolean flag1) {
		this.flag1 = flag1;
	}

	public boolean isFlag2() {
		return this.flag2;
	}

	public void setFlag2(boolean flag2) {
		this.flag2 = flag2;
	}

	public boolean isFlag3() {
		return this.flag3;
	}

	public void setFlag3(boolean flag3) {
		this.flag3 = flag3;
	}

	public boolean isFlag4() {
		return this.flag4;
	}

	public void setFlag4(boolean flag4) {
		this.flag4 = flag4;
	}

	public boolean isFlag5() {
		return this.flag5;
	}

	public void setFlag5(boolean flag5) {
		this.flag5 = flag5;
	}

	public boolean isFlag6() {
		return this.flag6;
	}

	public void setFlag6(boolean flag6) {
		this.flag6 = flag6;
	}

	public boolean isFlag7() {
		return this.flag7;
	}

	public void setFlag7(boolean flag7) {
		this.flag7 = flag7;
	}

	public boolean isFlag8() {
		return this.flag8;
	}

	public void setFlag8(boolean flag8) {
		this.flag8 = flag8;
	}

	public boolean isFlag9() {
		return this.flag9;
	}

	public void setFlag9(boolean flag9) {
		this.flag9 = flag9;
	}

	public boolean isFlag10() {
		return this.flag10;
	}

	public void setFlag10(boolean flag10) {
		this.flag10 = flag10;
	}

	public Solution(boolean flag1, boolean flag2, boolean flag3, boolean flag4,
			boolean flag5, boolean flag6, boolean flag7, boolean flag8,
			boolean flag9, boolean flag10) {
		this.flag1 = flag1;
		this.flag2 = flag2;
		this.flag3 = flag3;
		this.flag4 = flag4;
		this.flag5 = flag5;
		this.flag6 = flag6;
		this.flag7 = flag7;
		this.flag8 = flag8;
		this.flag9 = flag9;
		this.flag10 = flag10;
	}

}