package com.myspace.ecommerce;

import java.time.LocalTime;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
@javax.xml.bind.annotation.XmlRootElement
@org.kie.api.definition.type.PropertyReactive
public class VendorWorkingDays implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String vendorWD;

	private boolean todayFlag;

	private boolean todayOneFlag;

	private boolean todayTwoFlag;

	private boolean todayThreeFlag;

	private boolean todayFourFlag;

	private boolean todayFiveFlag;

	private boolean todaySixFlag;

	private LocalTime openTime;

	private LocalTime closeTime;

	private long product;

	private java.lang.String todayE;

	private java.lang.String todayOneE;

	private java.lang.String todayTwoE;

	private java.lang.String todayThreeE;

	private java.lang.String todayFiveE;

	private java.lang.String todaySixE;

	private java.lang.String todayM;

	private java.lang.String todayTwoM;

	private java.lang.String todayFourM;

	private java.lang.String todayFiveM;

	private java.lang.String todaySixM;

	private java.lang.String todayThreeM;

	private java.lang.String todayFourE;

	private java.lang.String todayOneM;

	private long service;

	private long productService;

	private int one;

	private java.lang.String now;

	@org.kie.api.definition.type.Key
	private boolean direct;

	private double km;

	private float lat1;

	private float lat2;

	private float long1;

	private float long2;

	private double sWeight;

	private java.lang.Float kgfactor;

	private java.lang.Float kmfactor;

	private java.lang.Float fixedcost;

	private java.lang.Float leadtime;

	private boolean freeDelivery;

	private java.util.List<java.lang.Float> length;

	private java.util.List<java.lang.Float> width;

	private java.util.List<java.lang.Float> height;

	private java.util.List<java.lang.Float> actualWeight;

	private Float suml;

	private Float sumh;

	private Float suma;

	private Float sumw;

	public VendorWorkingDays() {
	}

	public java.lang.String getVendorWD() {
		return this.vendorWD;
	}

	public void setVendorWD(java.lang.String vendorWD) {
		this.vendorWD = vendorWD;
	}

	public boolean isTodayFlag() {
		return this.todayFlag;
	}

	public void setTodayFlag(boolean todayFlag) {
		this.todayFlag = todayFlag;
	}

	public boolean isTodayOneFlag() {
		return this.todayOneFlag;
	}

	public void setTodayOneFlag(boolean todayOneFlag) {
		this.todayOneFlag = todayOneFlag;
	}

	public boolean isTodayTwoFlag() {
		return this.todayTwoFlag;
	}

	public void setTodayTwoFlag(boolean todayTwoFlag) {
		this.todayTwoFlag = todayTwoFlag;
	}

	public boolean isTodayThreeFlag() {
		return this.todayThreeFlag;
	}

	public void setTodayThreeFlag(boolean todayThreeFlag) {
		this.todayThreeFlag = todayThreeFlag;
	}

	public boolean isTodayFourFlag() {
		return this.todayFourFlag;
	}

	public void setTodayFourFlag(boolean todayFourFlag) {
		this.todayFourFlag = todayFourFlag;
	}

	public boolean isTodayFiveFlag() {
		return this.todayFiveFlag;
	}

	public void setTodayFiveFlag(boolean todayFiveFlag) {
		this.todayFiveFlag = todayFiveFlag;
	}

	public boolean isTodaySixFlag() {
		return this.todaySixFlag;
	}

	public void setTodaySixFlag(boolean todaySixFlag) {
		this.todaySixFlag = todaySixFlag;
	}

	public java.lang.String getTodayE() {
		return this.todayE;
	}

	public void setTodayE(java.lang.String todayE) {
		this.todayE = todayE;
	}

	public java.lang.String getTodayOneE() {
		return this.todayOneE;
	}

	public void setTodayOneE(java.lang.String todayOneE) {
		this.todayOneE = todayOneE;
	}

	public java.lang.String getTodayTwoE() {
		return this.todayTwoE;
	}

	public void setTodayTwoE(java.lang.String todayTwoE) {
		this.todayTwoE = todayTwoE;
	}

	public java.lang.String getTodayThreeE() {
		return this.todayThreeE;
	}

	public void setTodayThreeE(java.lang.String todayThreeE) {
		this.todayThreeE = todayThreeE;
	}

	public java.lang.String getTodayFiveE() {
		return this.todayFiveE;
	}

	public void setTodayFiveE(java.lang.String todayFiveE) {
		this.todayFiveE = todayFiveE;
	}

	public java.lang.String getTodaySixE() {
		return this.todaySixE;
	}

	public void setTodaySixE(java.lang.String todaySixE) {
		this.todaySixE = todaySixE;
	}

	public java.lang.String getTodayM() {
		return this.todayM;
	}

	public void setTodayM(java.lang.String todayM) {
		this.todayM = todayM;
	}

	public java.lang.String getTodayTwoM() {
		return this.todayTwoM;
	}

	public void setTodayTwoM(java.lang.String todayTwoM) {
		this.todayTwoM = todayTwoM;
	}

	public java.lang.String getTodayFourM() {
		return this.todayFourM;
	}

	public void setTodayFourM(java.lang.String todayFourM) {
		this.todayFourM = todayFourM;
	}

	public java.lang.String getTodayFiveM() {
		return this.todayFiveM;
	}

	public void setTodayFiveM(java.lang.String todayFiveM) {
		this.todayFiveM = todayFiveM;
	}

	public java.lang.String getTodaySixM() {
		return this.todaySixM;
	}

	public void setTodaySixM(java.lang.String todaySixM) {
		this.todaySixM = todaySixM;
	}

	public java.lang.String getTodayThreeM() {
		return this.todayThreeM;
	}

	public void setTodayThreeM(java.lang.String todayThreeM) {
		this.todayThreeM = todayThreeM;
	}

	public java.lang.String getTodayFourE() {
		return this.todayFourE;
	}

	public void setTodayFourE(java.lang.String todayFourE) {
		this.todayFourE = todayFourE;
	}

	public java.lang.String getTodayOneM() {
		return this.todayOneM;
	}

	public void setTodayOneM(java.lang.String todayOneM) {
		this.todayOneM = todayOneM;
	}

	public int getOne() {
		return this.one;
	}

	public void setOne(int one) {
		this.one = one;
	}

	public java.lang.String getNow() {
		return this.now;
	}

	public void setNow(java.lang.String now) {
		this.now = now;
	}

	public java.time.LocalTime getOpenTime() {
		return this.openTime;
	}

	public void setOpenTime(java.time.LocalTime openTime) {
		this.openTime = openTime;
	}

	public java.time.LocalTime getCloseTime() {
		return this.closeTime;
	}

	public void setCloseTime(java.time.LocalTime closeTime) {
		this.closeTime = closeTime;
	}

	public boolean isDirect() {
		return this.direct;
	}

	public void setDirect(boolean direct) {
		this.direct = direct;
	}

	public float getLat1() {
		return this.lat1;
	}

	public void setLat1(float lat1) {
		this.lat1 = lat1;
	}

	public float getLat2() {
		return this.lat2;
	}

	public void setLat2(float lat2) {
		this.lat2 = lat2;
	}

	public float getLong1() {
		return this.long1;
	}

	public void setLong1(float long1) {
		this.long1 = long1;
	}

	public float getLong2() {
		return this.long2;
	}

	public void setLong2(float long2) {
		this.long2 = long2;
	}

	public double getKm() {
		return this.km;
	}

	public void setKm(double km) {
		this.km = km;
	}

	public java.lang.Float getKgfactor() {
		return this.kgfactor;
	}

	public void setKgfactor(java.lang.Float kgfactor) {
		this.kgfactor = kgfactor;
	}

	public java.lang.Float getKmfactor() {
		return this.kmfactor;
	}

	public void setKmfactor(java.lang.Float kmfactor) {
		this.kmfactor = kmfactor;
	}

	public java.lang.Float getFixedcost() {
		return this.fixedcost;
	}

	public void setFixedcost(java.lang.Float fixedcost) {
		this.fixedcost = fixedcost;
	}

	public java.lang.Float getLeadtime() {
		return this.leadtime;
	}

	public void setLeadtime(java.lang.Float leadtime) {
		this.leadtime = leadtime;
	}

	public boolean isFreeDelivery() {
		return this.freeDelivery;
	}

	public void setFreeDelivery(boolean freeDelivery) {
		this.freeDelivery = freeDelivery;
	}

	public double getsWeight() {
		return this.sWeight;
	}

	public void setsWeight(double sWeight) {
		this.sWeight = sWeight;
	}

	public java.util.List<java.lang.Float> getLength() {
		return this.length;
	}

	public void setLength(java.util.List<java.lang.Float> length) {
		this.length = length;
	}

	public java.util.List<java.lang.Float> getWidth() {
		return this.width;
	}

	public void setWidth(java.util.List<java.lang.Float> width) {
		this.width = width;
	}

	public java.util.List<java.lang.Float> getHeight() {
		return this.height;
	}

	public void setHeight(java.util.List<java.lang.Float> height) {
		this.height = height;
	}

	public java.util.List<java.lang.Float> getActualWeight() {
		return this.actualWeight;
	}

	public void setActualWeight(java.util.List<java.lang.Float> actualWeight) {
		this.actualWeight = actualWeight;
	}

	public java.lang.Float getSuml() {
		return this.suml;
	}

	public void setSuml(java.lang.Float suml) {
		this.suml = suml;
	}

	public java.lang.Float getSumh() {
		return this.sumh;
	}

	public void setSumh(java.lang.Float sumh) {
		this.sumh = sumh;
	}

	public java.lang.Float getSuma() {
		return this.suma;
	}

	public void setSuma(java.lang.Float suma) {
		this.suma = suma;
	}

	public java.lang.Float getSumw() {
		return this.sumw;
	}

	public void setSumw(java.lang.Float sumw) {
		this.sumw = sumw;
	}

	public long getProductService() {
		return this.productService;
	}

	public void setProductService(long productService) {
		this.productService = productService;
	}

	public long getProduct() {
		return this.product;
	}

	public void setProduct(long product) {
		this.product = product;
	}

	public long getService() {
		return this.service;
	}

	public void setService(long service) {
		this.service = service;
	}

	public VendorWorkingDays(java.lang.String vendorWD, boolean todayFlag,
			boolean todayOneFlag, boolean todayTwoFlag, boolean todayThreeFlag,
			boolean todayFourFlag, boolean todayFiveFlag, boolean todaySixFlag,
			java.time.LocalTime openTime, java.time.LocalTime closeTime,
			long product, java.lang.String todayE, java.lang.String todayOneE,
			java.lang.String todayTwoE, java.lang.String todayThreeE,
			java.lang.String todayFiveE, java.lang.String todaySixE,
			java.lang.String todayM, java.lang.String todayTwoM,
			java.lang.String todayFourM, java.lang.String todayFiveM,
			java.lang.String todaySixM, java.lang.String todayThreeM,
			java.lang.String todayFourE, java.lang.String todayOneM,
			long service, long productService, int one, java.lang.String now,
			boolean direct, double km, float lat1, float lat2, float long1,
			float long2, double sWeight, java.lang.Float kgfactor,
			java.lang.Float kmfactor, java.lang.Float fixedcost,
			java.lang.Float leadtime, boolean freeDelivery,
			java.util.List<java.lang.Float> length,
			java.util.List<java.lang.Float> width,
			java.util.List<java.lang.Float> height,
			java.util.List<java.lang.Float> actualWeight, java.lang.Float suml,
			java.lang.Float sumh, java.lang.Float suma, java.lang.Float sumw) {
		this.vendorWD = vendorWD;
		this.todayFlag = todayFlag;
		this.todayOneFlag = todayOneFlag;
		this.todayTwoFlag = todayTwoFlag;
		this.todayThreeFlag = todayThreeFlag;
		this.todayFourFlag = todayFourFlag;
		this.todayFiveFlag = todayFiveFlag;
		this.todaySixFlag = todaySixFlag;
		this.openTime = openTime;
		this.closeTime = closeTime;
		this.product = product;
		this.todayE = todayE;
		this.todayOneE = todayOneE;
		this.todayTwoE = todayTwoE;
		this.todayThreeE = todayThreeE;
		this.todayFiveE = todayFiveE;
		this.todaySixE = todaySixE;
		this.todayM = todayM;
		this.todayTwoM = todayTwoM;
		this.todayFourM = todayFourM;
		this.todayFiveM = todayFiveM;
		this.todaySixM = todaySixM;
		this.todayThreeM = todayThreeM;
		this.todayFourE = todayFourE;
		this.todayOneM = todayOneM;
		this.service = service;
		this.productService = productService;
		this.one = one;
		this.now = now;
		this.direct = direct;
		this.km = km;
		this.lat1 = lat1;
		this.lat2 = lat2;
		this.long1 = long1;
		this.long2 = long2;
		this.sWeight = sWeight;
		this.kgfactor = kgfactor;
		this.kmfactor = kmfactor;
		this.fixedcost = fixedcost;
		this.leadtime = leadtime;
		this.freeDelivery = freeDelivery;
		this.length = length;
		this.width = width;
		this.height = height;
		this.actualWeight = actualWeight;
		this.suml = suml;
		this.sumh = sumh;
		this.suma = suma;
		this.sumw = sumw;
	}

	public VendorWorkingDays(boolean direct) {
		this.direct = direct;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;
		com.myspace.ecommerce.VendorWorkingDays that = (com.myspace.ecommerce.VendorWorkingDays) o;
		if (direct != that.direct)
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		int result = 17;
		result = 31 * result + (direct ? 1 : 0);
		return result;
	}

}